centos_6:
    spec: debian/shinken-mod-logstore-sqlite.spec
centos_7:
    spec: debian/shinken-mod-logstore-sqlite.spec
debian_7:
    debian: debian
debian_8:
    debian: debian
ubuntu_12.04:
    debian: debian
ubuntu_14.04:
    debian: debian
